# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build-test-github-action
run-name: hello ${{ github.actor }} !

on:
  push:
    branches: [ "main", "dev"]

permissions:
  contents: read

jobs:
  build: # name of job 
    runs-on: ubuntu-latest #configuration jobs build run on ubuntu latest
    steps:
    - uses: actions/checkout@v4
      with:
            python-version: '3.x'
            architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      
    - name: Install dependencies in requirement file
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build code 
      run: python3 hello-github-actions.py
